---
title: "Mini-Project 1"
author: Jack Tan
output: 
  html_document:
    toc: true
    toc_float: true
---
```{r message = FALSE}
library(ggplot2)
library(dplyr)
library(caret)
library(RANN)
library(stringr)
```

\
\
## Part 1: Ready the data
```{r}
airbnb <- read.csv("https://www.macalester.edu/~ajohns24/data/NYC_airbnb_kaggle.csv")
nbhd <- read.csv("https://www.macalester.edu/~ajohns24/data/NYC_nbhd_kaggle.csv")
airbnb_complete <- left_join(nbhd, airbnb, by = c("neighbourhood" = "neighbourhood_cleansed"))
dim(airbnb_complete)
```




deal with the data
```{r message = FALSE, warning= FALSE}
airbnb_complete <- airbnb_complete %>% 
  filter(price < 1000) %>%
  filter(host_response_rate != "") %>%
  mutate(amenity_count = str_count(amenities, ',') + 1) %>%
  #filter(host_is_superhost != "") %>%
  #filter(host_has_profile_pic != "") %>%
  #filter(host_response_time != "") %>%
  #filter(require_guest_profile_picture != )
  select(-id,-longitude,-latitude,-amenities,-square_feet,-calendar_updated)
dim(airbnb_complete)
```



```{r}
set.seed(253)
airbnb_5000 <- sample_n(airbnb_complete,5000)
dim(airbnb_5000)
```

\
\
\
\
\
\



## Part 2: Analyze
impute with KNN
```{r}
impute_info <- airbnb_5000 %>%
  select(-price) %>%
  preProcess(method = "knnImpute")
airbnb_5000 <- predict(impute_info, newdata = airbnb_5000)
```

model with LASSO
```{r}
lambda_grid <- 10^seq(-3, 1, length = 100)

# Set the seed 
    set.seed(253)
    
    lasso_model <- train(
      price ~ .,
      data = airbnb_5000,
      method = "glmnet",
      trControl = trainControl(method = "cv", number = 10, selectionFunction = "oneSE"),
      tuneGrid = data.frame(alpha = 1, lambda = lambda_grid),
      metric = "MAE",
      na.action = na.omit
    )
```

```{r message = FALSE}
model_coef <- coef(lasso_model$finalModel, lasso_model$bestTune$lambda)
model_coef
```


```{r message = FALSE}
airbnb_5000 <- airbnb_5000 %>% 
  select(-host_response_time,-host_response_rate,-host_is_superhost,-host_has_profile_pic,-is_location_exact,-property_type,-beds,-bed_type,-maximum_nights,-cancellation_policy,-require_guest_profile_picture,-neighbourhood)
```

```{r}
ls_model <- train(
    price ~ .,
    data = airbnb_5000,
    method = "lm",
    trControl = trainControl(method = "cv", number = 10),
    na.action = na.omit
)

summary(ls_model)
```

```{r}
airbnb_5000 <- airbnb_5000 %>% select(-room_type,-is_business_travel_ready,-instant_bookable)
```

```{r warning = FALSE, message = FALSE, fig.width = 8, fig.height = 12}
 # Set the seed
    set.seed(253)

 # Run the GAM
    gam_model <- train(
      price ~.,
      data = airbnb_5000,
      method = "gamLoess",
      tuneGrid = data.frame(span = seq(0.1,1,length = 10), degree = 1),
      trControl = trainControl(method = "cv", number = 10, selectionFunction = "best"),
      metric = "MAE",
      na.action = na.omit
    )
```

```{r fig.width = 8, fig.height =12}
    # Calculate the CV MAE of the best model
    gam_model$results %>% 
      filter(span == gam_model$bestTune$span)
    gam_model$resample %>% 
      summarize(mean(MAE))
    
     # Put the 11 plots in a 4x3 grid
    par(mfrow = c(4,3))
    
    # Make plots
    plot(gam_model$finalModel)
```
\
\
\
\
\
\



## Part 3: Summarize



\
\
\
\
\
\



## Part 4: Contributions



